In [2]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('db_basic_queries.sqlite3')

Es un estandar que los comandos propio de SQL los escribamos en mayúsculas.

In [3]:
query = """
SELECT * FROM pedidos
"""
# query = "select * from pedidos" # seleccionar todas las columnas(eso significa el *) de la tabla pedidos
pd.read_sql_query(query, conn)

,pedido_id,cliente_id,producto,cantidad,precio_unit,fecha_pedido,estado
0,101,1.0,Laptop,1,3500.0,2025-02-10,ENVIADO
1,102,1.0,Mouse,2,45.5,2025-02-10,ENTREGADO
2,103,2.0,Teclado,1,80.0,2025-03-25,PENDIENTE
3,104,3.0,Monitor,2,220.0,2024-12-01,CANCELADO
4,105,4.0,Smartphone,1,1200.0,2025-07-02,ENVIADO
5,106,5.0,Tablet,3,300.0,2025-06-20,ENTREGADO
6,107,2.0,Auriculares,1,65.0,2025-03-26,ENTREGADO
7,108,NaN,Webcam,1,70.0,2025-05-05,PENDIENTE

In [4]:
query = """
SELECT fecha_pedido, estado, producto FROM pedidos
""" # Seleccione las columnas fecha_pedido, estado y producto de la tabla pedidos
data = pd.read_sql_query(query, conn)
data

  fecha_pedido     estado     producto
0   2025-02-10    ENVIADO       Laptop
1   2025-02-10  ENTREGADO        Mouse
2   2025-03-25  PENDIENTE      Teclado
3   2024-12-01  CANCELADO      Monitor
4   2025-07-02    ENVIADO   Smartphone
5   2025-06-20  ENTREGADO       Tablet
6   2025-03-26  ENTREGADO  Auriculares
7   2025-05-05  PENDIENTE       Webcam

In [5]:
query = """
SELECT * FROM clientes
"""# Traiga todas las filas de todas las columnas de la table "clientes"
pd.read_sql_query(query, conn)

   cliente_id       nombre    ciudad  edad fecha_registro
0           1    Ana Gómez    Bogotá    34     2025-01-15
1           2   Luis Pérez  Medellín    28     2025-03-22
2           3   María Ruiz      Cali    41     2024-11-07
3           4  Juan Torres      None    22     2025-07-01
4           5   Carla León    Bogotá    29     2025-06-18

In [6]:
# cuales productos se han vendido?
query = """
SELECT DISTINCT estado FROM pedidos
""" # Quitar duplicados de la columna estado / traer valores únicosde la columna estado
pd.read_sql_query(query, conn)

      estado
0    ENVIADO
1  ENTREGADO
2  PENDIENTE
3  CANCELADO

In [7]:
# Lo anterior se puede hacer también con pandas directamente
query = """
SELECT estado FROM pedidos
""" # Quitar duplicados de la columna estado / traer valores únicosde la columna estado
data = pd.read_sql_query(query, conn)
display(data)
data.estado.unique() # Entrega los resultados como un Array de NumPy

      estado
0    ENVIADO
1  ENTREGADO
2  PENDIENTE
3  CANCELADO
4    ENVIADO
5  ENTREGADO
6  ENTREGADO
7  PENDIENTE

array(['ENVIADO', 'ENTREGADO', 'PENDIENTE', 'CANCELADO'], dtype=object)

In [8]:
# cuales son los clientes mayores de 30 años?
query = """
SELECT
  nombre,
  edad
FROM clientes
WHERE edad > 30
"""
pd.read_sql_query(query, conn)

       nombre  edad
0   Ana Gómez    34
1  María Ruiz    41

In [9]:
# cuales pedidos se entregaron minimamente en febrero del 2025 y tienen estado de entregado
query = """
SELECT *
FROM pedidos
WHERE fecha_pedido > '2025-02-01' AND estado = 'ENTREGADO'
""" # Se debe tener cuidado con el formato de las fechas
# Cuando se hacen filtro con comparación de igualdad, se debe tener cuidado con las mayúsculas
pd.read_sql_query(query, conn)

,pedido_id,cliente_id,producto,cantidad,precio_unit,fecha_pedido,estado
0,102,1,Mouse,2,45.5,2025-02-10,ENTREGADO
1,106,5,Tablet,3,300.0,2025-06-20,ENTREGADO
2,107,2,Auriculares,1,65.0,2025-03-26,ENTREGADO

In [10]:
# Devolver todos los pedidos que han sido cancelados o pendientes
query = """
 SELECT * FROM pedidos WHERE estado IN ('CANCELADO','PENDIENTE')
"""
#query = """
#SELECT * FROM pedidos WHERE estado = 'CANCELADO' OR estado = 'PENDIENTE'
#"""
pd.read_sql_query(query, conn)

,pedido_id,cliente_id,producto,cantidad,precio_unit,fecha_pedido,estado
0,103,2.0,Teclado,1,80.0,2025-03-25,PENDIENTE
1,104,3.0,Monitor,2,220.0,2024-12-01,CANCELADO
2,108,NaN,Webcam,1,70.0,2025-05-05,PENDIENTE

In [11]:
# Cuales son los clientes que se registraron en Q1 2025
query = """
SELECT * FROM clientes WHERE fecha_registro BETWEEN '2025-01-01' AND '2025-03-31'
""" # Se filtra en el intervalo [a,b]
pd.read_sql_query(query, conn)

   cliente_id      nombre    ciudad  edad fecha_registro
0           1   Ana Gómez    Bogotá    34     2025-01-15
1           2  Luis Pérez  Medellín    28     2025-03-22

In [12]:
query = """
SELECT * FROM pedidos
""" # Mostremos todos los datos de pedidos para poder validar la siguiente consulta
pd.read_sql_query(query, conn)

,pedido_id,cliente_id,producto,cantidad,precio_unit,fecha_pedido,estado
0,101,1.0,Laptop,1,3500.0,2025-02-10,ENVIADO
1,102,1.0,Mouse,2,45.5,2025-02-10,ENTREGADO
2,103,2.0,Teclado,1,80.0,2025-03-25,PENDIENTE
3,104,3.0,Monitor,2,220.0,2024-12-01,CANCELADO
4,105,4.0,Smartphone,1,1200.0,2025-07-02,ENVIADO
5,106,5.0,Tablet,3,300.0,2025-06-20,ENTREGADO
6,107,2.0,Auriculares,1,65.0,2025-03-26,ENTREGADO
7,108,NaN,Webcam,1,70.0,2025-05-05,PENDIENTE

In [13]:
# Cual es la cantidad total, minima, maxima y promedio de articulos vendidos por el estado actual
# de la compra
query = """
SELECT
        estado,
        SUM(cantidad) AS total_cantidad,
        MIN(cantidad) AS min_cantidad,
        MAX(cantidad) AS max_cantidad,
        AVG(cantidad) AS avg_cantidad,
        COUNT(cantidad) AS count_cantidad
FROM pedidos
GROUP BY estado
"""
# Cuando se emplea el comando GROUP BY se debe cumplir con lo siguiente:
# - Las columnas a la derecha GROUP BY son las columnas que deben ir después de SELECT
# - En el SELECT, después de las columnas que aparecen en el GROUP BY, se colocan funciones de agregación: SUM, MIN, MAX, AVG, COUNT
pd.read_sql_query(query, conn)

,estado,total_cantidad,min_cantidad,max_cantidad,avg_cantidad,count_cantidad
0,CANCELADO,2,2,2,2.0,1
1,ENTREGADO,6,1,3,2.0,3
2,ENVIADO,2,1,1,1.0,2
3,PENDIENTE,2,1,1,1.0,2

In [14]:
# Cual es el precio unitario minimo, maximo y promedio de articulos vendidos por el estado actual
# de la compra
query = """
SELECT
    estado,
    MIN(precio_unit) AS min_precio_unit,
    MAX(precio_unit) AS max_precio_unit,
    ROUND(AVG(precio_unit),2) AS avg_precio_unit
FROM pedidos
GROUP BY estado
"""
pd.read_sql_query(query, conn)

      estado  min_precio_unit  max_precio_unit  avg_precio_unit
0  CANCELADO            220.0            220.0           220.00
1  ENTREGADO             45.5            300.0           136.83
2    ENVIADO           1200.0           3500.0          2350.00
3  PENDIENTE             70.0             80.0            75.00

In [15]:
# Cual es el estado que presenta una cantidad de productos total mayor a 5
query = """
SELECT
        estado,
        SUM(cantidad) AS total_cantidad
FROM pedidos
GROUP BY estado
HAVING total_cantidad > 5
"""
# HAVING: filtro que se aplica a los resultados de los GROUP BY
pd.read_sql_query(query, conn)

      estado  total_cantidad
0  ENTREGADO               6

In [16]:
query = """
SELECT
  *
FROM pedidos
WHERE producto in ('Laptop','Mouse','Teclado')
"""
pd.read_sql_query(query, conn)

,pedido_id,cliente_id,producto,cantidad,precio_unit,fecha_pedido,estado
0,101,1,Laptop,1,3500.0,2025-02-10,ENVIADO
1,102,1,Mouse,2,45.5,2025-02-10,ENTREGADO
2,103,2,Teclado,1,80.0,2025-03-25,PENDIENTE

In [17]:
# Cuales el total de productos vendidos cuando el estado es ENTREGADO para Laptops, mouse y teclado
query = """
SELECT
        estado,
        SUM(cantidad) AS total_cantidad
FROM pedidos
WHERE producto in ('Laptop','Mouse','Teclado') AND estado = 'ENTREGADO'
GROUP BY estado
"""
pd.read_sql_query(query, conn)

      estado  total_cantidad
0  ENTREGADO               2

In [18]:
# Cuales el total de productos vendidos cuando para Laptops, mouse y teclado, independiente del estado y que su cantidad
# total sea igual a 1
query = """
SELECT
        estado,
        SUM(cantidad) AS total_cantidad
FROM pedidos
WHERE producto in ('Laptop','Mouse','Teclado')
GROUP BY estado
HAVING total_cantidad = 1
"""

# WHERE filtra antes de hacer la agrupación y having despues de hacer la agrupación

pd.read_sql_query(query, conn)

      estado  total_cantidad
0    ENVIADO               1
1  PENDIENTE               1

In [19]:
# Deme la lista de los ultimos 3 clientes registrados
query = """
SELECT
  nombre, fecha_registro
FROM
  clientes
ORDER BY fecha_registro DESC
LIMIT 3
"""
# LIMIT hace que solo se vea N cantidad de filas
pd.read_sql_query(query, conn)

        nombre fecha_registro
0  Juan Torres     2025-07-01
1   Carla León     2025-06-18
2   Luis Pérez     2025-03-22

In [20]:
# Cuales son los clientes con ordenes de precio unitario mayor a 1000
query = """
SELECT
  nombre
FROM
  pedidos B
  inner JOIN clientes A
    ON A.cliente_id = B.cliente_id
WHERE precio_unit > 1000
"""
# se le brinda un alias a la tabla pedidos, se llamará B y Clientes A

pd.read_sql_query(query, conn)

        nombre
0    Ana Gómez
1  Juan Torres

# Clase 3

In [21]:
# Muestre la tabla de pedidos pero creando la columna categoria_valor, donde tiene que
# devolver ALTO en el caso en el que el precio unitario supere 1000, si está entre 200 y 1000 debe ser NORMAL
# y para todo caso contrario, colocar BAJO.
query = """
SELECT
  precio_unit,
  CASE
    WHEN precio_unit > 1000
      THEN 'ALTO'
    WHEN precio_unit < 1000 AND precio_unit >= 200
      THEN 'NORMAL'
  ELSE 'BAJO'
  END AS categoria_valor 
FROM
  pedidos
"""
# si no se pone el nombre de la columna (categoria_valor) el código pone un nombre largo raro.
pd.read_sql_query(query, conn)

   precio_unit categoria_valor
0       3500.0            ALTO
1         45.5            BAJO
2         80.0            BAJO
3        220.0          NORMAL
4       1200.0            ALTO
5        300.0          NORMAL
6         65.0            BAJO
7         70.0            BAJO

¿Qué pedidos con estado “ENVIADO” o “ENTREGADO” tienen más de una unidad y fueron realizados entre el 1 de enero y el 30 de junio de 2025?

In [22]:
query = """
SELECT
  *
FROM pedidos
WHERE estado IN ('ENVIADO','ENTREGADO')
AND cantidad > 1 AND fecha_pedido BETWEEN '2025-01-01' AND '2025-06-30'
"""
pd.read_sql_query(query, conn)

,pedido_id,cliente_id,producto,cantidad,precio_unit,fecha_pedido,estado
0,102,1,Mouse,2,45.5,2025-02-10,ENTREGADO
1,106,5,Tablet,3,300.0,2025-06-20,ENTREGADO

¿Qué clientes han hecho más de un pedido, y cuál es el número de pedidos y el total gastado por cada uno?

In [23]:
query = """
SELECT
  A.cliente_id,
  COUNT(A.cliente_id) AS numero_pedidos,
  SUM(cantidad*precio_unit) AS total_gastado
FROM clientes A
INNER JOIN pedidos B
  ON A.cliente_id = B.cliente_id
GROUP BY A.cliente_id
HAVING numero_pedidos > 1
"""
pd.read_sql_query(query, conn)

   cliente_id  numero_pedidos  total_gastado
0           1               2         3591.0
1           2               2          145.0

¿Cómo se clasifica el nivel de gasto de cada cliente en “ALTO”, “MEDIO” o “BAJO”, según el total que ha gastado?

In [30]:
query = """
SELECT
  cliente_id,
  SUM(cantidad*precio_unit) AS total
FROM
  pedidos
GROUP BY cliente_id
ORDER BY total DESC
"""
pd.read_sql_query(query, conn)

   cliente_id   total
0         1.0  3591.0
1         4.0  1200.0
2         5.0   900.0
3         3.0   440.0
4         2.0   145.0
5         NaN    70.0

In [31]:
query = """
WITH total_clientes AS
(
SELECT
  cliente_id,
  SUM(cantidad*precio_unit) AS total
FROM
  pedidos
GROUP BY cliente_id
)
SELECT
  cliente_id,
  total,
  CASE
    WHEN total >= 1000
      THEN 'ALTO'
    WHEN total > 400
      THEN 'MEDIO'
    ELSE 'BAJO'
  END AS categoria
FROM total_clientes
"""

# With me segmenta o me crea sub tablas para ejecutar como en pequeños pasos, para hacer subconsultas
pd.read_sql_query(query, conn)

   cliente_id   total categoria
0         NaN    70.0      BAJO
1         1.0  3591.0      ALTO
2         2.0   145.0      BAJO
3         3.0   440.0     MEDIO
4         4.0  1200.0      ALTO
5         5.0   900.0     MEDIO

¿Cuáles son las ciudades únicas de los clientes (no nulas), ordenadas alfabéticamente? Muestre los resultados(filas) 2,3 y 4, es decir, muestre tres resultados a partir del segundo.

In [ ]:
query = """
SELECT DISTINCT
  ciudad
FROM clientes
WHERE ciudad IS NOT NULL
ORDER BY ciudad ASC
LIMIT 3
OFFSET 1
"""

# DISTINCT borra las variables repetidas
# LIMIT me limita las filas que puedo ver, solo me deja ver X cantidad de cosas
# OFFSET ejecutar el limite apartir de una fila X y no desde la primera fila

pd.read_sql_query(query, conn)

     ciudad
0      Cali
1  Medellín