# Taller  SQL

## Base de datos para ejecutar comandos del taller

In [1]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('taller_sql.sqlite3')
cur = conn.cursor()

cur.executescript("""
DROP TABLE IF EXISTS empleados;
DROP TABLE IF EXISTS ventas;

CREATE TABLE empleados (
    empleado_id INTEGER PRIMARY KEY,
    nombre TEXT,
    departamento TEXT,
    ciudad TEXT,
    salario REAL,
    fecha_contratacion TEXT
);

CREATE TABLE ventas (
    venta_id INTEGER PRIMARY KEY,
    empleado_id INTEGER,
    producto TEXT,
    categoria TEXT,
    cantidad INTEGER,
    precio_unit REAL,
    fecha_venta TEXT,
    estado TEXT
);
""")

empleados = [
    (1, 'Ana Ramírez', 'Ventas', 'Bogotá', 3200000, '2022-03-10'),
    (2, 'Carlos Vega', 'Marketing', 'Medellín', 2900000, '2021-07-22'),
    (3, 'Diana Soto', 'Ventas', 'Cali', 3100000, '2023-01-15'),
    (4, 'Felipe Cruz', 'IT', 'Bogotá', 4200000, '2020-11-05'),
    (5, 'Gabriela Ríos', 'IT', None, 4500000, '2023-06-30'),
    (6, 'Hugo Mendoza', 'Ventas', 'Medellín', 2950000, '2022-09-12'),
    (7, 'Isabel Nava', 'Marketing', 'Bogotá', 3000000, '2021-02-18'),
    (8, 'Jorge Paredes', 'Finanzas', 'Cali', 3800000, '2023-03-25'),
    (9, 'Karla Duarte', 'Finanzas', 'Bogotá', 3900000, '2022-12-01'),
    (10, 'Luis Ortega', 'IT', 'Medellín', 4100000, '2021-08-09'),
]

ventas = [
    (1, 1, 'Laptop', 'Tecnología', 1, 3500000, '2024-01-15', 'ENTREGADO'),
    (2, 1, 'Mouse', 'Tecnología', 3, 45000, '2024-01-15', 'ENTREGADO'),
    (3, 3, 'Silla Oficina', 'Mobiliario', 2, 250000, '2024-02-20', 'ENVIADO'),
    (4, 4, 'Monitor', 'Tecnología', 1, 650000, '2023-11-05', 'CANCELADO'),
    (5, 6, 'Escritorio', 'Mobiliario', 1, 480000, '2024-03-10', 'ENTREGADO'),
    (6, 2, 'Camiseta Corp', 'Merch', 10, 25000, '2024-01-30', 'ENTREGADO'),
    (7, 3, 'Teclado', 'Tecnología', 2, 90000, '2024-04-02', 'PENDIENTE'),
    (8, None, 'Impresora', 'Tecnología', 1, 700000, '2024-02-11', 'ENTREGADO'),
    (9, 7, 'Cuaderno', 'Papelería', 20, 3000, '2024-03-18', 'ENTREGADO'),
    (10, 9, 'Silla Oficina', 'Mobiliario', 1, 250000, '2024-05-01', 'ENVIADO'),
    (11, 1, 'Monitor', 'Tecnología', 2, 650000, '2024-05-15', 'ENTREGADO'),
    (12, 6, 'Camiseta Corp', 'Merch', 5, 25000, '2024-06-01', 'ENTREGADO'),
    (13, 10, 'Laptop', 'Tecnología', 1, 3500000, '2024-06-20', 'PENDIENTE'),
    (14, 8, 'Escritorio', 'Mobiliario', 2, 480000, '2024-02-28', 'CANCELADO'),
    (15, 4, 'Cuaderno', 'Papelería', 15, 3000, '2024-07-10', 'ENTREGADO'),
    (16, 3, 'Mouse', 'Tecnología', 4, 45000, '2024-07-15', 'ENTREGADO'),
    (17, 5, 'Teclado', 'Tecnología', 1, 90000, '2024-08-05', 'ENVIADO'),
    (18, 2, 'Silla Oficina', 'Mobiliario', 3, 250000, '2024-08-12', 'ENTREGADO'),
    (19, 9, 'Monitor', 'Tecnología', 1, 650000, '2024-01-22', 'ENTREGADO'),
    (20, 7, 'Laptop', 'Tecnología', 1, 3500000, '2024-09-01', 'ENVIADO'),
]

cur.executemany("INSERT INTO empleados VALUES (?,?,?,?,?,?)", empleados)
cur.executemany("INSERT INTO ventas VALUES (?,?,?,?,?,?,?,?)", ventas)
conn.commit()

print("Base de datos creada. Tablas disponibles: empleados, ventas")

Base de datos creada. Tablas disponibles: empleados, ventas

Exploremos las tablas disponibles antes de empezar:

In [2]:
pd.read_sql_query("SELECT * FROM empleados", conn)

,empleado_id,nombre,departamento,ciudad,salario,fecha_contratacion
0,1,Ana Ramírez,Ventas,Bogotá,3200000.0,2022-03-10
1,2,Carlos Vega,Marketing,Medellín,2900000.0,2021-07-22
2,3,Diana Soto,Ventas,Cali,3100000.0,2023-01-15
3,4,Felipe Cruz,IT,Bogotá,4200000.0,2020-11-05
4,5,Gabriela Ríos,IT,NaN,4500000.0,2023-06-30
5,6,Hugo Mendoza,Ventas,Medellín,2950000.0,2022-09-12
6,7,Isabel Nava,Marketing,Bogotá,3000000.0,2021-02-18
7,8,Jorge Paredes,Finanzas,Cali,3800000.0,2023-03-25
8,9,Karla Duarte,Finanzas,Bogotá,3900000.0,2022-12-01
9,10,Luis Ortega,IT,Medellín,4100000.0,2021-08-09

In [3]:
pd.read_sql_query("SELECT * FROM ventas", conn)

,venta_id,empleado_id,producto,categoria,cantidad,precio_unit,fecha_venta,estado
0,1,1.0,Laptop,Tecnología,1,3500000.0,2024-01-15,ENTREGADO
1,2,1.0,Mouse,Tecnología,3,45000.0,2024-01-15,ENTREGADO
2,3,3.0,Silla Oficina,Mobiliario,2,250000.0,2024-02-20,ENVIADO
3,4,4.0,Monitor,Tecnología,1,650000.0,2023-11-05,CANCELADO
4,5,6.0,Escritorio,Mobiliario,1,480000.0,2024-03-10,ENTREGADO
5,6,2.0,Camiseta Corp,Merch,10,25000.0,2024-01-30,ENTREGADO
6,7,3.0,Teclado,Tecnología,2,90000.0,2024-04-02,PENDIENTE
7,8,NaN,Impresora,Tecnología,1,700000.0,2024-02-11,ENTREGADO
8,9,7.0,Cuaderno,Papelería,20,3000.0,2024-03-18,ENTREGADO
9,10,9.0,Silla Oficina,Mobiliario,1,250000.0,2024-05-01,ENVIADO
10,11,1.0,Monitor,Tecnología,2,650000.0,2024-05-15,ENTREGADO
11,12,6.0,Camiseta Corp,Merch,5,25000.0,2024-06-01,ENTREGADO
12,13,10.0,Laptop,Tecnología,1,3500000.0,2024-06-20,PENDIENTE
13,14,8.0,Escritorio,Mobiliario,2,480000.0,2024-02-28,CANCELADO
14,15,4.0,Cuaderno,Papelería,15,3000.0,2024-07-10,ENTREGADO
15,16,3.0,Mouse,Tecnología,4,45000.0,2024-07-15,ENTREGADO
16,17,5.0,Teclado,Tecnología,1,90000.0,2024-08-05,ENVIADO
17,18,2.0,Silla Oficina,Mobiliario,3,250000.0,2024-08-12,ENTREGADO
18,19,9.0,Monitor,Tecnología,1,650000.0,2024-01-22,ENTREGADO
19,20,7.0,Laptop,Tecnología,1,3500000.0,2024-09-01,ENVIADO

## Preguntas

### Pregunta 1

In [ ]:
#CREATE
query = """
CREATE TABLE IF NOT EXISTS bonificaciones (
    bonificacion_id INTEGER PRIMARY KEY,
    empleado_id INTEGER,
    monto REAL,
    fecha TEXT
)
"""
cur.execute(query)
conn.commit()

query2 = """
SELECT * FROM bonificaciones 

"""
pd.read_sql_query(query2, conn)

Empty DataFrame
Columns: [bonificacion_id, empleado_id, monto, fecha]
Index: []

In [ ]:
#ALTER
query = """
ALTER TABLE bonificaciones ADD COLUMN activo INTEGER DEFAULT 1

"""
cur.execute(query)
conn.commit()

In [ ]:
#DROP y SELECT
query = """
DROP TABLE IF EXISTS bonificaciones

"""
cur.execute(query)
conn.commit()

query2 = """
SELECT * FROM bonificaciones
"""
pd.read_sql_query(query2, conn)

In [ ]:
#INSERT
query = """
INSERT INTO bonificaciones (empleado_id, monto, fecha, activo)
VALUES (1, 150000, '2024-06-15', 1)
"""
cur.execute(query)
conn.commit()

pd.read_sql_query("SELECT * FROM bonificaciones", conn)

   bonificacion_id  empleado_id     monto       fecha  activo
0                1            1  150000.0  2024-06-15       1

In [ ]:
#UPDATE
query = """
UPDATE bonificaciones
SET monto = 200000
WHERE empleado_id = 1
"""
cur.execute(query)
conn.commit()

pd.read_sql_query("SELECT * FROM bonificaciones WHERE empleado_id = 1", conn)

   bonificacion_id  empleado_id     monto       fecha  activo
0                1            1  200000.0  2024-06-15       1

In [ ]:
#DELETE
query = """
DELETE FROM bonificaciones
WHERE empleado_id = 1
"""
cur.execute(query)
conn.commit()

pd.read_sql_query("SELECT * FROM bonificaciones", conn)

### Pregunta 2

In [11]:
pd.read_sql_query("SELECT * FROM empleados", conn)

,empleado_id,nombre,departamento,ciudad,salario,fecha_contratacion
0,1,Ana Ramírez,Ventas,Bogotá,3200000.0,2022-03-10
1,2,Carlos Vega,Marketing,Medellín,2900000.0,2021-07-22
2,3,Diana Soto,Ventas,Cali,3100000.0,2023-01-15
3,4,Felipe Cruz,IT,Bogotá,4200000.0,2020-11-05
4,5,Gabriela Ríos,IT,NaN,4500000.0,2023-06-30
5,6,Hugo Mendoza,Ventas,Medellín,2950000.0,2022-09-12
6,7,Isabel Nava,Marketing,Bogotá,3000000.0,2021-02-18
7,8,Jorge Paredes,Finanzas,Cali,3800000.0,2023-03-25
8,9,Karla Duarte,Finanzas,Bogotá,3900000.0,2022-12-01
9,10,Luis Ortega,IT,Medellín,4100000.0,2021-08-09

In [12]:
pd.read_sql_query("SELECT * FROM ventas", conn)

,venta_id,empleado_id,producto,categoria,cantidad,precio_unit,fecha_venta,estado
0,1,1.0,Laptop,Tecnología,1,3500000.0,2024-01-15,ENTREGADO
1,2,1.0,Mouse,Tecnología,3,45000.0,2024-01-15,ENTREGADO
2,3,3.0,Silla Oficina,Mobiliario,2,250000.0,2024-02-20,ENVIADO
3,4,4.0,Monitor,Tecnología,1,650000.0,2023-11-05,CANCELADO
4,5,6.0,Escritorio,Mobiliario,1,480000.0,2024-03-10,ENTREGADO
5,6,2.0,Camiseta Corp,Merch,10,25000.0,2024-01-30,ENTREGADO
6,7,3.0,Teclado,Tecnología,2,90000.0,2024-04-02,PENDIENTE
7,8,NaN,Impresora,Tecnología,1,700000.0,2024-02-11,ENTREGADO
8,9,7.0,Cuaderno,Papelería,20,3000.0,2024-03-18,ENTREGADO
9,10,9.0,Silla Oficina,Mobiliario,1,250000.0,2024-05-01,ENVIADO
10,11,1.0,Monitor,Tecnología,2,650000.0,2024-05-15,ENTREGADO
11,12,6.0,Camiseta Corp,Merch,5,25000.0,2024-06-01,ENTREGADO
12,13,10.0,Laptop,Tecnología,1,3500000.0,2024-06-20,PENDIENTE
13,14,8.0,Escritorio,Mobiliario,2,480000.0,2024-02-28,CANCELADO
14,15,4.0,Cuaderno,Papelería,15,3000.0,2024-07-10,ENTREGADO
15,16,3.0,Mouse,Tecnología,4,45000.0,2024-07-15,ENTREGADO
16,17,5.0,Teclado,Tecnología,1,90000.0,2024-08-05,ENVIADO
17,18,2.0,Silla Oficina,Mobiliario,3,250000.0,2024-08-12,ENTREGADO
18,19,9.0,Monitor,Tecnología,1,650000.0,2024-01-22,ENTREGADO
19,20,7.0,Laptop,Tecnología,1,3500000.0,2024-09-01,ENVIADO

In [ ]:
#ROW_NUMBER
query = """
SELECT
    v.venta_id,
    e.nombre AS vendedor,
    v.producto,
    v.cantidad * v.precio_unit AS monto,
    ROW_NUMBER() OVER (
        PARTITION BY e.nombre
        ORDER BY v.cantidad * v.precio_unit DESC
    ) AS num_venta
FROM ventas v
INNER JOIN empleados e ON e.empleado_id = v.empleado_id
"""
pd.read_sql_query(query, conn)

    venta_id       vendedor       producto      monto  num_venta
0          1    Ana Ramírez         Laptop  3500000.0          1
1         11    Ana Ramírez        Monitor  1300000.0          2
2          2    Ana Ramírez          Mouse   135000.0          3
3         18    Carlos Vega  Silla Oficina   750000.0          1
4          6    Carlos Vega  Camiseta Corp   250000.0          2
5          3     Diana Soto  Silla Oficina   500000.0          1
6          7     Diana Soto        Teclado   180000.0          2
7         16     Diana Soto          Mouse   180000.0          3
8          4    Felipe Cruz        Monitor   650000.0          1
9         15    Felipe Cruz       Cuaderno    45000.0          2
10        17  Gabriela Ríos        Teclado    90000.0          1
11         5   Hugo Mendoza     Escritorio   480000.0          1
12        12   Hugo Mendoza  Camiseta Corp   125000.0          2
13        20    Isabel Nava         Laptop  3500000.0          1
14         9    Isabel Nava       Cuaderno    60000.0          2
15        14  Jorge Paredes     Escritorio   960000.0          1
16        19   Karla Duarte        Monitor   650000.0          1
17        10   Karla Duarte  Silla Oficina   250000.0          2
18        13    Luis Ortega         Laptop  3500000.0          1

In [ ]:
#RANK
query = """
SELECT
    v.venta_id,
    v.categoria,
    v.cantidad * v.precio_unit AS monto,
    RANK() OVER (
        PARTITION BY v.categoria
        ORDER BY v.cantidad * v.precio_unit DESC
    ) AS ranking
FROM ventas v
"""
pd.read_sql_query(query, conn)

    venta_id   categoria      monto  ranking
0          6       Merch   250000.0        1
1         12       Merch   125000.0        2
2         14  Mobiliario   960000.0        1
3         18  Mobiliario   750000.0        2
4          3  Mobiliario   500000.0        3
5          5  Mobiliario   480000.0        4
6         10  Mobiliario   250000.0        5
7          9   Papelería    60000.0        1
8         15   Papelería    45000.0        2
9          1  Tecnología  3500000.0        1
10        13  Tecnología  3500000.0        1
11        20  Tecnología  3500000.0        1
12        11  Tecnología  1300000.0        4
13         8  Tecnología   700000.0        5
14         4  Tecnología   650000.0        6
15        19  Tecnología   650000.0        6
16         7  Tecnología   180000.0        8
17        16  Tecnología   180000.0        8
18         2  Tecnología   135000.0       10
19        17  Tecnología    90000.0       11

In [ ]:
#SUMA
query = """
SELECT
    v.venta_id,
    e.nombre AS vendedor,
    v.fecha_venta,
    v.cantidad * v.precio_unit AS monto,
    SUM(v.cantidad * v.precio_unit) OVER (
        PARTITION BY e.nombre
        ORDER BY v.fecha_venta
    ) AS acumulado
FROM ventas v
INNER JOIN empleados e ON e.empleado_id = v.empleado_id
"""
pd.read_sql_query(query, conn)

    venta_id       vendedor fecha_venta      monto  acumulado
0          1    Ana Ramírez  2024-01-15  3500000.0  3635000.0
1          2    Ana Ramírez  2024-01-15   135000.0  3635000.0
2         11    Ana Ramírez  2024-05-15  1300000.0  4935000.0
3          6    Carlos Vega  2024-01-30   250000.0   250000.0
4         18    Carlos Vega  2024-08-12   750000.0  1000000.0
5          3     Diana Soto  2024-02-20   500000.0   500000.0
6          7     Diana Soto  2024-04-02   180000.0   680000.0
7         16     Diana Soto  2024-07-15   180000.0   860000.0
8          4    Felipe Cruz  2023-11-05   650000.0   650000.0
9         15    Felipe Cruz  2024-07-10    45000.0   695000.0
10        17  Gabriela Ríos  2024-08-05    90000.0    90000.0
11         5   Hugo Mendoza  2024-03-10   480000.0   480000.0
12        12   Hugo Mendoza  2024-06-01   125000.0   605000.0
13         9    Isabel Nava  2024-03-18    60000.0    60000.0
14        20    Isabel Nava  2024-09-01  3500000.0  3560000.0
15        14  Jorge Paredes  2024-02-28   960000.0   960000.0
16        19   Karla Duarte  2024-01-22   650000.0   650000.0
17        10   Karla Duarte  2024-05-01   250000.0   900000.0
18        13    Luis Ortega  2024-06-20  3500000.0  3500000.0

In [24]:
#AVG - OVER
query = """
SELECT
    v.venta_id,
    v.categoria,
    v.cantidad * v.precio_unit AS monto,
    ROUND(AVG(v.cantidad * v.precio_unit) OVER (PARTITION BY v.categoria), 2) AS promedio_categoria
FROM ventas v
"""
pd.read_sql_query(query, conn)

    venta_id   categoria      monto  promedio_categoria
0          6       Merch   250000.0           187500.00
1         12       Merch   125000.0           187500.00
2          3  Mobiliario   500000.0           588000.00
3          5  Mobiliario   480000.0           588000.00
4         10  Mobiliario   250000.0           588000.00
5         14  Mobiliario   960000.0           588000.00
6         18  Mobiliario   750000.0           588000.00
7          9   Papelería    60000.0            52500.00
8         15   Papelería    45000.0            52500.00
9          1  Tecnología  3500000.0          1307727.27
10         2  Tecnología   135000.0          1307727.27
11         4  Tecnología   650000.0          1307727.27
12         7  Tecnología   180000.0          1307727.27
13         8  Tecnología   700000.0          1307727.27
14        11  Tecnología  1300000.0          1307727.27
15        13  Tecnología  3500000.0          1307727.27
16        16  Tecnología   180000.0          1307727.27
17        17  Tecnología    90000.0          1307727.27
18        19  Tecnología   650000.0          1307727.27
19        20  Tecnología  3500000.0          1307727.27

# Punto 3

Como ejemplo para probar las operaciones de conjunto voy a tomar los empleados que vendieron en el 1er semestre y 2do semestre de 2024

In [8]:
pd.read_sql_query("SELECT * FROM ventas", conn)

,venta_id,empleado_id,producto,categoria,cantidad,precio_unit,fecha_venta,estado
0,1,1.0,Laptop,Tecnología,1,3500000.0,2024-01-15,ENTREGADO
1,2,1.0,Mouse,Tecnología,3,45000.0,2024-01-15,ENTREGADO
2,3,3.0,Silla Oficina,Mobiliario,2,250000.0,2024-02-20,ENVIADO
3,4,4.0,Monitor,Tecnología,1,650000.0,2023-11-05,CANCELADO
4,5,6.0,Escritorio,Mobiliario,1,480000.0,2024-03-10,ENTREGADO
5,6,2.0,Camiseta Corp,Merch,10,25000.0,2024-01-30,ENTREGADO
6,7,3.0,Teclado,Tecnología,2,90000.0,2024-04-02,PENDIENTE
7,8,NaN,Impresora,Tecnología,1,700000.0,2024-02-11,ENTREGADO
8,9,7.0,Cuaderno,Papelería,20,3000.0,2024-03-18,ENTREGADO
9,10,9.0,Silla Oficina,Mobiliario,1,250000.0,2024-05-01,ENVIADO
10,11,1.0,Monitor,Tecnología,2,650000.0,2024-05-15,ENTREGADO
11,12,6.0,Camiseta Corp,Merch,5,25000.0,2024-06-01,ENTREGADO
12,13,10.0,Laptop,Tecnología,1,3500000.0,2024-06-20,PENDIENTE
13,14,8.0,Escritorio,Mobiliario,2,480000.0,2024-02-28,CANCELADO
14,15,4.0,Cuaderno,Papelería,15,3000.0,2024-07-10,ENTREGADO
15,16,3.0,Mouse,Tecnología,4,45000.0,2024-07-15,ENTREGADO
16,17,5.0,Teclado,Tecnología,1,90000.0,2024-08-05,ENVIADO
17,18,2.0,Silla Oficina,Mobiliario,3,250000.0,2024-08-12,ENTREGADO
18,19,9.0,Monitor,Tecnología,1,650000.0,2024-01-22,ENTREGADO
19,20,7.0,Laptop,Tecnología,1,3500000.0,2024-09-01,ENVIADO

In [ ]:
# UNION, empleados que vendieron en el 1er semestre O en el 2do, sin repetir
query = """
SELECT empleado_id FROM ventas WHERE fecha_venta < '2024-07-01'
UNION
SELECT empleado_id FROM ventas WHERE fecha_venta >= '2024-07-01'
"""
pd.read_sql_query(query, conn)

    empleado_id
0           NaN
1           1.0
2           2.0
3           3.0
4           4.0
5           5.0
6           6.0
7           7.0
8           8.0
9           9.0
10         10.0

In [ ]:
# UNION ALL, lo mismo que pasa con UNION pero con duplicados (el que vendió en ambos semestres aparece 2 veces)
query = """
SELECT empleado_id FROM ventas WHERE fecha_venta < '2024-07-01'
UNION ALL
SELECT empleado_id FROM ventas WHERE fecha_venta >= '2024-07-01'
"""
pd.read_sql_query(query, conn)

    empleado_id
0           1.0
1           1.0
2           3.0
3           4.0
4           6.0
5           2.0
6           3.0
7           NaN
8           7.0
9           9.0
10          1.0
11          6.0
12         10.0
13          8.0
14          9.0
15          4.0
16          3.0
17          5.0
18          2.0
19          7.0

In [ ]:
#INTERSECT, muestra los  empleados que vendieron en AMBOS semestres
query = """
SELECT empleado_id FROM ventas WHERE fecha_venta < '2024-07-01'
INTERSECT
SELECT empleado_id FROM ventas WHERE fecha_venta >= '2024-07-01'
"""
pd.read_sql_query(query, conn)

   empleado_id
0            2
1            3
2            4
3            7

In [11]:
#EXCEPT, muestra los empleados que vendieron en el 1er semestre pero NO en el 2do
query = """
SELECT empleado_id FROM ventas WHERE fecha_venta < '2024-07-01'
EXCEPT
SELECT empleado_id FROM ventas WHERE fecha_venta >= '2024-07-01'
"""
pd.read_sql_query(query, conn)

   empleado_id
0          NaN
1          1.0
2          6.0
3          8.0
4          9.0
5         10.0

# Pregunta 4

In [5]:
import sqlite3
import pandas as pd

conn2 = sqlite3.connect('db_minitest.sqlite3')
cur = conn2.cursor()
query = """
SELECT name FROM sqlite_master WHERE type='table'
"""
pd.read_sql_query(query, conn2)

       name
0     users
1  profiles
2    orders

In [7]:
pd.read_sql_query("SELECT * FROM users", conn2)

   user_id     name  age                email  created_at
0        1    Alice   30    alice@example.com  2025-01-10
1        2      Bob   22      bob@example.com  2025-02-20
2        3  Charlie   45  charlie@example.com  2024-12-05
3        4    Diana   35    diana@example.com  2025-03-15
4        5   Edward   55   edward@example.com  2025-04-10
5        6    Fiona   27    fiona@example.com  2025-05-12
6        7   George   19   george@example.com  2024-10-30
7        8   Hannah   42   hannah@example.com  2025-06-01

In [8]:
pd.read_sql_query("SELECT * FROM profiles", conn2)

   user_id        address     phone
0        1    123 Main St  555-1234
1        2     456 Elm St  555-5678
2        3     789 Oak St  555-9012
3        4    321 Pine St  555-3456
4        5  654 Cedar Ave  555-7890
5        6   987 Birch Rd  555-2345
6        7  246 Spruce Ln  555-6789
7        8  135 Willow Dr  555-0123

In [9]:
pd.read_sql_query("SELECT * FROM orders", conn2)

    order_id  user_id      product  amount  order_date
0       1001        1       Laptop  1200.0  2025-02-01
1       1002        1        Mouse    25.5  2025-02-15
2       1003        2     Keyboard    75.0  2025-03-01
3       1004        3      Monitor   300.0  2024-12-20
4       1005        4       Tablet   450.0  2025-03-20
5       1006        4   Headphones    85.0  2025-03-25
6       1007        4       Webcam    55.0  2025-04-01
7       1008        5       Camera   500.0  2025-04-15
8       1009        5       Tripod    80.0  2025-04-16
9       1010        6         Lens   200.0  2025-05-15
10      1011        6          Bag    50.0  2025-05-16
11      1012        6       Filter    30.0  2025-05-17
12      1013        7  Memory Card    45.0  2024-11-05
13      1014        8   Smartwatch   250.0  2025-06-05
14      1015        8      Charger    20.0  2025-06-06

In [ ]:
# Usuarios y registros recientes. Nota: si se usaba como referencia la fecha actual (2026) la consulta devolvia datos vacíos, por lo que se toma como referencia el año 2025.
query = """
SELECT
    u.name,
    u.email,
    p.phone,
    p.address,
    u.created_at
FROM users u
INNER JOIN profiles p ON p.user_id = u.user_id
WHERE u.age > 30
  AND strftime('%Y', u.created_at) = '2025'
ORDER BY u.created_at ASC
LIMIT 5
"""
pd.read_sql_query(query, conn2)

     name               email     phone        address  created_at
0   Diana   diana@example.com  555-3456    321 Pine St  2025-03-15
1  Edward  edward@example.com  555-7890  654 Cedar Ave  2025-04-10
2  Hannah  hannah@example.com  555-0123  135 Willow Dr  2025-06-01

In [25]:
# Gasto acumulado por cliente
query = """
SELECT
    u.user_id,
    u.name,
    SUM(o.amount) AS gasto_total
FROM users u
INNER JOIN orders o ON o.user_id = u.user_id
GROUP BY u.user_id, u.name
HAVING SUM(o.amount) > 700
ORDER BY gasto_total DESC
"""
pd.read_sql_query(query, conn2)

   user_id   name  gasto_total
0        1  Alice       1225.5

In [ ]:
# Ciudades activas
query = """
    SELECT p.address
    FROM profiles p
    INNER JOIN orders o ON o.user_id = p.user_id
    GROUP BY p.user_id, p.address
    HAVING COUNT(o.order_id) >= 2
"""
pd.read_sql_query(query, conn2)

         address
0    123 Main St
1    321 Pine St
2  654 Cedar Ave
3   987 Birch Rd
4  135 Willow Dr

In [ ]:
#Segmentación demográfica
query = """
SELECT
    CASE
        WHEN age < 25 THEN 'Joven'
        WHEN age BETWEEN 25 AND 40 THEN 'Adulto'
        ELSE 'Senior'
    END AS grupo_edad,
    COUNT(*) AS numero_usuarios
FROM users
GROUP BY grupo_edad
"""
pd.read_sql_query(query, conn2)

  grupo_edad  numero_usuarios
0     Adulto                3
1      Joven                2
2     Senior                3

In [ ]:
#Informe combinado de usuarios y pedidos
query = """
SELECT
    u.user_id,
    u.name,
    u.email,
    u.age,
    p.address,
    p.phone,
    o.order_id,
    o.product,
    o.amount,
    o.order_date
FROM users u
INNER JOIN profiles p ON p.user_id = u.user_id
INNER JOIN orders o ON o.user_id = u.user_id
ORDER BY o.order_date DESC
"""

pd.read_sql_query(query, conn2)

,user_id,name,email,age,address,phone,order_id,product,amount,order_date
0,8,Hannah,hannah@example.com,42,135 Willow Dr,555-0123,1015,Charger,20.0,2025-06-06
1,8,Hannah,hannah@example.com,42,135 Willow Dr,555-0123,1014,Smartwatch,250.0,2025-06-05
2,6,Fiona,fiona@example.com,27,987 Birch Rd,555-2345,1012,Filter,30.0,2025-05-17
3,6,Fiona,fiona@example.com,27,987 Birch Rd,555-2345,1011,Bag,50.0,2025-05-16
4,6,Fiona,fiona@example.com,27,987 Birch Rd,555-2345,1010,Lens,200.0,2025-05-15
5,5,Edward,edward@example.com,55,654 Cedar Ave,555-7890,1009,Tripod,80.0,2025-04-16
6,5,Edward,edward@example.com,55,654 Cedar Ave,555-7890,1008,Camera,500.0,2025-04-15
7,4,Diana,diana@example.com,35,321 Pine St,555-3456,1007,Webcam,55.0,2025-04-01
8,4,Diana,diana@example.com,35,321 Pine St,555-3456,1006,Headphones,85.0,2025-03-25
9,4,Diana,diana@example.com,35,321 Pine St,555-3456,1005,Tablet,450.0,2025-03-20
10,2,Bob,bob@example.com,22,456 Elm St,555-5678,1003,Keyboard,75.0,2025-03-01
11,1,Alice,alice@example.com,30,123 Main St,555-1234,1002,Mouse,25.5,2025-02-15
12,1,Alice,alice@example.com,30,123 Main St,555-1234,1001,Laptop,1200.0,2025-02-01
13,3,Charlie,charlie@example.com,45,789 Oak St,555-9012,1004,Monitor,300.0,2024-12-20
14,7,George,george@example.com,19,246 Spruce Ln,555-6789,1013,Memory Card,45.0,2024-11-05

## Pregunta 6

### Numeral d

In [8]:
import sqlite3
import pandas as pd

conn = sqlite3.connect(':memory:')
cur = conn.cursor()
cur.executescript("""
CREATE TABLE dim_tiempo (
    date_key         INTEGER PRIMARY KEY,   -- formato yyyymmdd
    full_date        DATE NOT NULL,
    dia              INTEGER,
    dia_semana       VARCHAR(10),
    semana           INTEGER,
    mes              INTEGER,
    nombre_mes       VARCHAR(15),
    trimestre        INTEGER,
    año             INTEGER,
    es_fin_de_semana  BOOLEAN,
    es_festivo        BOOLEAN
);

CREATE TABLE dim_geografia (
    geo_key       INTEGER PRIMARY KEY,
    ciudad        VARCHAR(50),
    departamento  VARCHAR(50),
    pais          VARCHAR(50),
    region        VARCHAR(50),
    codigo_postal VARCHAR(10),
    latitud       DECIMAL(9,6),
    longitud      DECIMAL(9,6)
);

CREATE TABLE fact_ventas (
    sale_id       INTEGER PRIMARY KEY,
    date_key      INTEGER REFERENCES dim_tiempo(date_key),
    geo_key       INTEGER REFERENCES dim_geografia(geo_key),
    product_key   INTEGER,
    customer_key  INTEGER,
    quantity      INTEGER,
    unit_price    DECIMAL(12,2),
    total_amount  DECIMAL(12,2)
);
""")
conn.commit()
pd.read_sql_query("SELECT name FROM sqlite_master WHERE type='table'", conn)

            name
0     dim_tiempo
1  dim_geografia
2    fact_ventas

In [9]:
pd.read_sql_query("SELECT * FROM dim_tiempo",conn)

Empty DataFrame
Columns: [date_key, full_date, dia, dia_semana, semana, mes, nombre_mes, trimestre, año, es_fin_de_semana, es_festivo]
Index: []

In [7]:
pd.read_sql_query("SELECT * FROM dim_geografia",conn)

Empty DataFrame
Columns: [geo_key, ciudad, departamento, pais, region, codigo_postal, latitud, longitud]
Index: []

In [10]:
pd.read_sql_query("SELECT * FROM fact_ventas",conn)

Empty DataFrame
Columns: [sale_id, date_key, geo_key, product_key, customer_key, quantity, unit_price, total_amount]
Index: []

## Punto 7

In [1]:
#1NF todos los datos son atómicos y 2NF
import sqlite3
import pandas as pd
df = pd.read_csv(r'C:\Users\HP\Desktop\Fund_Data_Analysis\Taller_SQL_1\sales.csv', sep=';', encoding='latin1')

print("Tabla original sales.csv:")
df
df

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\HP\\Desktop\\Fund_Data_Analysis\\Taller_SQL_1\\sales.csv'

In [ ]:
conn3 = sqlite3.connect(':memory:')
cur = conn3.cursor()
cur.executescript("""
CREATE TABLE customers (
    customer_id   VARCHAR(10) PRIMARY KEY,
    customer_name VARCHAR(100) NOT NULL,
    customer_city VARCHAR(60)
);

CREATE TABLE products (
    product_id   VARCHAR(10) PRIMARY KEY,
    product_name VARCHAR(100) NOT NULL,
    category     VARCHAR(50)
);

CREATE TABLE reps (
    rep_id   VARCHAR(10) PRIMARY KEY,
    rep_name VARCHAR(100) NOT NULL,
    region   VARCHAR(50)
);


CREATE TABLE sale_items (
    sale_id    INTEGER NOT NULL REFERENCES sales(sale_id),
    product_id VARCHAR(10) NOT NULL REFERENCES products(product_id),
    quantity   INTEGER NOT NULL CHECK (quantity > 0),
    unit_price DECIMAL(12,2) NOT NULL CHECK (unit_price >= 0),
    PRIMARY KEY (sale_id, product_id)
);


CREATE TABLE sales (
    sale_id     INTEGER PRIMARY KEY,
    sale_date   DATE NOT NULL,
    customer_id VARCHAR(10) NOT NULL REFERENCES customers(customer_id),
    rep_id      VARCHAR(10) NOT NULL REFERENCES reps(rep_id)
);

""")

customers  = df[['customer_id','customer_name','customer_city']].drop_duplicates().sort_values('customer_id')
products   = df[['product_id','product_name','category']].drop_duplicates().sort_values('product_id')
reps       = df[['rep_id','rep_name','region']].drop_duplicates().sort_values('rep_id')
sales      = df[['sale_id','sale_date','customer_id','rep_id']].drop_duplicates().sort_values('sale_id')
sale_items = df[['sale_id','product_id','quantity','unit_price']].sort_values('sale_id')

customers.to_sql('customers', conn3, if_exists='append', index=False)
products.to_sql('products', conn3, if_exists='append', index=False)
reps.to_sql('reps', conn3, if_exists='append', index=False)
sales.to_sql('sales', conn3, if_exists='append', index=False)
sale_items.to_sql('sale_items', conn3, if_exists='append', index=False)

conn3.commit()

In [ ]:
pd.read_sql_query("SELECT * FROM customers", conn3)

  customer_id     customer_name customer_city
0        C001       María Gómez        Bogotá
1        C002  Andrés Rodríguez      Medellín
2        C003     Luis Martínez          Cali
3        C004       Ana Beltrán  Barranquilla
4        C005    Pedro Castillo        Bogotá
5        C006     Carla Mendoza     Cartagena
6        C007       Diego López   Bucaramanga
7        C008      Sofía García        Bogotá
8        C009       Javier Ruiz      Medellín
9        C010   Natalia Jiménez          Cali

In [ ]:
pd.read_sql_query("SELECT * FROM products", conn3)

  product_id      product_name        category
0       P100  Teclado Mecánico     Periféricos
1       P101      Mouse Óptico     Periféricos
2       P200       Monitor 24?       Pantallas
3       P300           SSD 1TB  Almacenamiento
4       P400         Webcam HD     Periféricos
5       P500    Disco Duro 2TB  Almacenamiento

In [ ]:
pd.read_sql_query("SELECT * FROM reps", conn3)

  rep_id       rep_name    region
0    R10     Juan Pérez    Andina
1    R11  Laura Sánchez  Pacífico
2    R12  Camila Torres  Pacífico

In [ ]:
pd.read_sql_query("SELECT * FROM sale_items", conn3)

    sale_id product_id  quantity  unit_price
0      1001       P100         2        1200
1      1002       P101         1         455
2      1003       P200         1        3500
3      1004       P300         3         900
4      1005       P100         1        1200
5      1006       P300         2         900
6      1007       P101         4         455
7      1008       P200         2        3500
8      1009       P400         1         700
9      1010       P500         2        1100
10     1011       P200         1        3500
11     1012       P100         3        1200
12     1013       P101         5         455
13     1014       P200         1        3500
14     1015       P400         2         700
15     1016       P500         1        1100
16     1017       P300         3         900
17     1018       P100         1        1200
18     1019       P101         2         455
19     1020       P200         1        3500

In [ ]:
pd.read_sql_query("SELECT * FROM sales", conn3)

    sale_id   sale_date customer_id rep_id
0      1001   1/07/2025        C001    R10
1      1002   2/07/2025        C002    R11
2      1003   2/07/2025        C001    R10
3      1004   3/07/2025        C003    R12
4      1005   4/07/2025        C004    R11
5      1006   5/07/2025        C005    R10
6      1007   6/07/2025        C006    R12
7      1008   7/07/2025        C007    R11
8      1009   8/07/2025        C008    R10
9      1010   9/07/2025        C009    R11
10     1011  10/07/2025        C010    R12
11     1012  11/07/2025        C002    R11
12     1013  12/07/2025        C003    R12
13     1014  13/07/2025        C004    R11
14     1015  14/07/2025        C005    R10
15     1016  15/07/2025        C006    R12
16     1017  16/07/2025        C007    R11
17     1018  17/07/2025        C008    R10
18     1019  18/07/2025        C009    R11
19     1020  19/07/2025        C010    R12

## Punto 7 b

In [ ]:
cur.executescript("""
CREATE TABLE dim_customer (
    customer_id   VARCHAR(10) PRIMARY KEY,
    customer_name VARCHAR(100),
    customer_city VARCHAR(60)
);
 
CREATE TABLE dim_product (
    product_id   VARCHAR(10) PRIMARY KEY,
    product_name VARCHAR(100),
    category     VARCHAR(50)
);
 
CREATE TABLE dim_reps (
    rep_id   VARCHAR(10) PRIMARY KEY,
    rep_name VARCHAR(100),
    region   VARCHAR(50)
);
 
CREATE TABLE dim_date (
    date_key  INTEGER PRIMARY KEY,
    full_date DATE
);
 
CREATE TABLE fact_sales (
    sale_id      INTEGER NOT NULL,
    product_id   VARCHAR(10) NOT NULL REFERENCES dim_product(product_id),
    date_key     INTEGER REFERENCES dim_date(date_key),
    customer_id  VARCHAR(10) REFERENCES dim_customer(customer_id),
    rep_id       VARCHAR(10) REFERENCES dim_rep(rep_id),
    quantity     INTEGER,
    unit_price   DECIMAL(12,2),
    total_amount DECIMAL(12,2), 
    PRIMARY KEY (sale_id, product_id)
);

""")
conn3.commit()

In [ ]:
cur.execute("""
INSERT INTO dim_date (date_key, full_date)
SELECT DISTINCT
    CAST(strftime('%Y%m%d', sale_date) AS INTEGER),
    sale_date
FROM sales;
""")
conn3.commit()

pd.read_sql_query("SELECT * FROM dim_date ORDER BY date_key", conn3)

    date_key   full_date
0          1   1/07/2025
1          2   2/07/2025
2          3   3/07/2025
3          4   4/07/2025
4          5   5/07/2025
5          6   6/07/2025
6          7   7/07/2025
7          8   8/07/2025
8          9   9/07/2025
9         10  10/07/2025
10        11  11/07/2025
11        12  12/07/2025
12        13  13/07/2025
13        14  14/07/2025
14        15  15/07/2025
15        16  16/07/2025
16        17  17/07/2025
17        18  18/07/2025
18        19  19/07/2025

In [ ]:
cur.execute("""
INSERT INTO fact_sales (sale_id, product_id, date_key, customer_id, rep_id, quantity, unit_price, total_amount)
SELECT
    s.sale_id,
    si.product_id,
    d.date_key,
    s.customer_id,
    s.rep_id,
    si.quantity,
    si.unit_price,
    si.quantity * si.unit_price
FROM sales s
INNER JOIN
    sale_items si ON si.sale_id = s.sale_id
INNER JOIN
    dim_date d ON d.full_date = s.sale_date
""")    
conn3.commit()

pd.read_sql_query("SELECT * FROM fact_sales", conn3)

,sale_id,product_id,date_key,customer_id,rep_id,quantity,unit_price,total_amount
0,1001,P100,1,C001,R10,2,1200,2400
1,1002,P101,2,C002,R11,1,455,455
2,1003,P200,2,C001,R10,1,3500,3500
3,1004,P300,3,C003,R12,3,900,2700
4,1005,P100,4,C004,R11,1,1200,1200
5,1006,P300,5,C005,R10,2,900,1800
6,1007,P101,6,C006,R12,4,455,1820
7,1008,P200,7,C007,R11,2,3500,7000
8,1009,P400,8,C008,R10,1,700,700
9,1010,P500,9,C009,R11,2,1100,2200
10,1011,P200,10,C010,R12,1,3500,3500
11,1012,P100,11,C002,R11,3,1200,3600
12,1013,P101,12,C003,R12,5,455,2275
13,1014,P200,13,C004,R11,1,3500,3500
14,1015,P400,14,C005,R10,2,700,1400
15,1016,P500,15,C006,R12,1,1100,1100
16,1017,P300,16,C007,R11,3,900,2700
17,1018,P100,17,C008,R10,1,1200,1200
18,1019,P101,18,C009,R11,2,455,910
19,1020,P200,19,C010,R12,1,3500,3500